# -*- coding: utf-8 -*-
"""GENERADO por tools/gen_names.py desde PokeAPI - no editar a mano.

Nombres oficiales localizados de FR, DE y ZH para la Pokedex gen 1.
FR/DE se normalizan a ASCII; ZH conserva sus caracteres Unicode.
"""

LOCAL_NAMES = {
    1: {'fr': 'BULBIZARRE', 'de': 'BISASAM', 'zh': '妙蛙种子'},
    2: {'fr': 'HERBIZARRE', 'de': 'BISAKNOSP', 'zh': '妙蛙草'},
    3: {'fr': 'FLORIZARRE', 'de': 'BISAFLOR', 'zh': '妙蛙花'},
    4: {'fr': 'SALAMECHE', 'de': 'GLUMANDA', 'zh': '小火龙'},
    5: {'fr': 'REPTINCEL', 'de': 'GLUTEXO', 'zh': '火恐龙'},
    6: {'fr': 'DRACAUFEU', 'de': 'GLURAK', 'zh': '喷火龙'},
    7: {'fr': 'CARAPUCE', 'de': 'SCHIGGY', 'zh': '杰尼龟'},
    8: {'fr': 'CARABAFFE', 'de': 'SCHILLOK', 'zh': '卡咪龟'},
    9: {'fr': 'TORTANK', 'de': 'TURTOK', 'zh': '水箭龟'},
    10: {'fr': 'CHENIPAN', 'de': 'RAUPY', 'zh': '绿毛虫'},
    11: {'fr': 'CHRYSACIER', 'de': 'SAFCON', 'zh': '铁甲蛹'},
    12: {'fr': 'PAPILUSION', 'de': 'SMETTBO', 'zh': '巴大蝶'},
    13: {'fr': 'ASPICOT', 'de': 'HORNLIU', 'zh': '独角虫'},
    14: {'fr': 'COCONFORT', 'de': 'KOKUNA', 'zh': '铁壳蛹'},
    15: {'fr': 'DARDARGNAN', 'de': 'BIBOR', 'zh': '大针蜂'},
    16: {'fr': 'ROUCOOL', 'de': 'TAUBSI', 'zh': '波波'},
    17: {'fr': 'ROUCOUPS', 'de': 'TAUBOGA', 'zh': '比比鸟'},
    18: {'fr': 'ROUCARNAGE', 'de': 'TAUBOSS', 'zh': '大比鸟'},
    19: {'de': 'RATTFRATZ', 'zh': '小拉达'},
    20: {'fr': 'RATTATAC', 'de': 'RATTIKARL', 'zh': '拉达'},
    21: {'fr': 'PIAFABEC', 'de': 'HABITAK', 'zh': '烈雀'},
    22: {'fr': 'RAPASDEPIC', 'de': 'IBITAK', 'zh': '大嘴雀'},
    23: {'fr': 'ABO', 'de': 'RETTAN', 'zh': '阿柏蛇'},
    24: {'zh': '阿柏怪'},
    25: {'zh': '皮卡丘'},
    26: {'zh': '雷丘'},
    27: {'fr': 'SABELETTE', 'de': 'SANDAN', 'zh': '穿山鼠'},
    28: {'fr': 'SABLAIREAU', 'de': 'SANDAMER', 'zh': '穿山王'},
    29: {'zh': '尼多兰'},
    30: {'zh': '尼多娜'},
    31: {'zh': '尼多后'},
    32: {'zh': '尼多朗'},
    33: {'zh': '尼多力诺'},
    34: {'zh': '尼多王'},
    35: {'fr': 'MELOFEE', 'de': 'PIEPI', 'zh': '皮皮'},
    36: {'fr': 'MELODELFE', 'de': 'PIXI', 'zh': '皮可西'},
    37: {'fr': 'GOUPIX', 'zh': '六尾'},
    38: {'fr': 'FEUNARD', 'de': 'VULNONA', 'zh': '九尾'},
    39: {'fr': 'RONDOUDOU', 'de': 'PUMMELUFF', 'zh': '胖丁'},
    40: {'fr': 'GRODOUDOU', 'de': 'KNUDDELUFF', 'zh': '胖可丁'},
    41: {'fr': 'NOSFERAPTI', 'zh': '超音蝠'},
    42: {'fr': 'NOSFERALTO', 'zh': '大嘴蝠'},
    43: {'fr': 'MYSTHERBE', 'de': 'MYRAPLA', 'zh': '走路草'},
    44: {'fr': 'ORTIDE', 'de': 'DUFLOR', 'zh': '臭臭花'},
    45: {'fr': 'RAFFLESIA', 'de': 'GIFLOR', 'zh': '霸王花'},
    46: {'zh': '派拉斯'},
    47: {'de': 'PARASEK', 'zh': '派拉斯特'},
    48: {'fr': 'MIMITOSS', 'de': 'BLUZUK', 'zh': '毛球'},
    49: {'fr': 'AEROMITE', 'de': 'OMOT', 'zh': '摩鲁蛾'},
    50: {'fr': 'TAUPIQUEUR', 'de': 'DIGDA', 'zh': '地鼠'},
    51: {'fr': 'TRIOPIKEUR', 'de': 'DIGDRI', 'zh': '三地鼠'},
    52: {'fr': 'MIAOUSS', 'de': 'MAUZI', 'zh': '喵喵'},
    53: {'de': 'SNOBILIKAT', 'zh': '猫老大'},
    54: {'fr': 'PSYKOKWAK', 'de': 'ENTON', 'zh': '可达鸭'},
    55: {'fr': 'AKWAKWAK', 'de': 'ENTORON', 'zh': '哥达鸭'},
    56: {'fr': 'FEROSINGE', 'de': 'MENKI', 'zh': '猴怪'},
    57: {'fr': 'COLOSSINGE', 'de': 'RASAFF', 'zh': '火暴猴'},
    58: {'fr': 'CANINOS', 'de': 'FUKANO', 'zh': '卡蒂狗'},
    59: {'fr': 'ARCANIN', 'de': 'ARKANI', 'zh': '风速狗'},
    60: {'fr': 'PTITARD', 'de': 'QUAPSEL', 'zh': '蚊香蝌蚪'},
    61: {'fr': 'TETARTE', 'de': 'QUAPUTZI', 'zh': '蚊香君'},
    62: {'fr': 'TARTARD', 'de': 'QUAPPO', 'zh': '蚊香泳士'},
    63: {'zh': '凯西'},
    64: {'zh': '勇基拉'},
    65: {'de': 'SIMSALA', 'zh': '胡地'},
    66: {'fr': 'MACHOC', 'de': 'MACHOLLO', 'zh': '腕力'},
    67: {'fr': 'MACHOPEUR', 'de': 'MASCHOCK', 'zh': '豪力'},
    68: {'fr': 'MACKOGNEUR', 'de': 'MACHOMEI', 'zh': '怪力'},
    69: {'fr': 'CHETIFLOR', 'de': 'KNOFENSA', 'zh': '喇叭芽'},
    70: {'fr': 'BOUSTIFLOR', 'de': 'ULTRIGARIA', 'zh': '口呆花'},
    71: {'fr': 'EMPIFLOR', 'de': 'SARZENIA', 'zh': '大食花'},
    72: {'de': 'TENTACHA', 'zh': '玛瑙水母'},
    73: {'de': 'TENTOXA', 'zh': '毒刺水母'},
    74: {'fr': 'RACAILLOU', 'de': 'KLEINSTEIN', 'zh': '小拳石'},
    75: {'fr': 'GRAVALANCH', 'de': 'GEOROK', 'zh': '隆隆石'},
    76: {'fr': 'GROLEM', 'de': 'GEOWAZ', 'zh': '隆隆岩'},
    77: {'de': 'PONITA', 'zh': '小火马'},
    78: {'fr': 'GALOPA', 'de': 'GALLOPA', 'zh': '烈焰马'},
    79: {'fr': 'RAMOLOSS', 'de': 'FLEGMON', 'zh': '呆呆兽'},
    80: {'fr': 'FLAGADOSS', 'de': 'LAHMUS', 'zh': '呆壳兽'},
    81: {'fr': 'MAGNETI', 'de': 'MAGNETILO', 'zh': '小磁怪'},
    82: {'zh': '三合一磁怪'},
    83: {'fr': 'CANARTICHO', 'de': 'PORENTA', 'zh': '大葱鸭'},
    84: {'de': 'DODU', 'zh': '嘟嘟'},
    85: {'de': 'DODRI', 'zh': '嘟嘟利'},
    86: {'fr': 'OTARIA', 'de': 'JUROB', 'zh': '小海狮'},
    87: {'fr': 'LAMANTINE', 'de': 'JUGONG', 'zh': '白海狮'},
    88: {'fr': 'TADMORV', 'de': 'SLEIMA', 'zh': '臭泥'},
    89: {'fr': 'GROTADMORV', 'de': 'SLEIMOK', 'zh': '臭臭泥'},
    90: {'fr': 'KOKIYAS', 'de': 'MUSCHAS', 'zh': '大舌贝'},
    91: {'fr': 'CRUSTABRI', 'de': 'AUSTOS', 'zh': '刺甲贝'},
    92: {'fr': 'FANTOMINUS', 'de': 'NEBULAK', 'zh': '鬼斯'},
    93: {'fr': 'SPECTRUM', 'de': 'ALPOLLO', 'zh': '鬼斯通'},
    94: {'fr': 'ECTOPLASMA', 'zh': '耿鬼'},
    95: {'zh': '大岩蛇'},
    96: {'fr': 'SOPORIFIK', 'de': 'TRAUMATO', 'zh': '催眠貘'},
    97: {'fr': 'HYPNOMADE', 'zh': '引梦貘人'},
    98: {'zh': '大钳蟹'},
    99: {'fr': 'KRABBOSS', 'zh': '巨钳蟹'},
    100: {'fr': 'VOLTORBE', 'de': 'VOLTOBAL', 'zh': '霹雳电球'},
    101: {'de': 'LEKTROBAL', 'zh': '顽皮雷弹'},
    102: {'fr': 'NOEUNOEUF', 'de': 'OWEI', 'zh': '蛋蛋'},
    103: {'fr': 'NOADKOKO', 'de': 'KOKOWEI', 'zh': '椰蛋树'},
    104: {'fr': 'OSSELAIT', 'de': 'TRAGOSSO', 'zh': '卡拉卡拉'},
    105: {'fr': 'OSSATUEUR', 'de': 'KNOGGA', 'zh': '嘎啦嘎啦'},
    106: {'fr': 'KICKLEE', 'de': 'KICKLEE', 'zh': '飞腿郎'},
    107: {'fr': 'TYGNON', 'de': 'NOCKCHAN', 'zh': '快拳郎'},
    108: {'fr': 'EXCELANGUE', 'de': 'SCHLURP', 'zh': '大舌头'},
    109: {'fr': 'SMOGO', 'de': 'SMOGON', 'zh': '瓦斯弹'},
    110: {'fr': 'SMOGOGO', 'de': 'SMOGMOG', 'zh': '双弹瓦斯'},
    111: {'fr': 'RHINOCORNE', 'de': 'RIHORN', 'zh': '独角犀牛'},
    112: {'fr': 'RHINOFEROS', 'de': 'RIZEROS', 'zh': '钻角犀兽'},
    113: {'fr': 'LEVEINARD', 'de': 'CHANEIRA', 'zh': '吉利蛋'},
    114: {'fr': 'SAQUEDENEU', 'zh': '蔓藤怪'},
    115: {'fr': 'KANGOUREX', 'de': 'KANGAMA', 'zh': '袋兽'},
    116: {'fr': 'HYPOTREMPE', 'de': 'SEEPER', 'zh': '墨海马'},
    117: {'fr': 'HYPOCEAN', 'de': 'SEEMON', 'zh': '海刺龙'},
    118: {'fr': 'POISSIRENE', 'de': 'GOLDINI', 'zh': '角金鱼'},
    119: {'fr': 'POISSOROY', 'de': 'GOLKING', 'zh': '金鱼王'},
    120: {'fr': 'STARI', 'de': 'STERNDU', 'zh': '海星星'},
    121: {'fr': 'STAROSS', 'zh': '宝石海星'},
    122: {'fr': 'M. MIME', 'de': 'PANTIMOS', 'zh': '魔墙人偶'},
    123: {'fr': 'INSECATEUR', 'de': 'SICHLOR', 'zh': '飞天螳螂'},
    124: {'fr': 'LIPPOUTOU', 'de': 'ROSSANA', 'zh': '迷唇姐'},
    125: {'fr': 'ELEKTEK', 'de': 'ELEKTEK', 'zh': '电击兽'},
    126: {'zh': '鸭嘴火兽'},
    127: {'fr': 'SCARABRUTE', 'zh': '凯罗斯'},
    128: {'zh': '肯泰罗'},
    129: {'fr': 'MAGICARPE', 'de': 'KARPADOR', 'zh': '鲤鱼王'},
    130: {'fr': 'LEVIATOR', 'de': 'GARADOS', 'zh': '暴鲤龙'},
    131: {'fr': 'LOKHLASS', 'zh': '拉普拉斯'},
    132: {'fr': 'METAMORPH', 'zh': '百变怪'},
    133: {'fr': 'EVOLI', 'de': 'EVOLI', 'zh': '伊布'},
    134: {'fr': 'AQUALI', 'de': 'AQUANA', 'zh': '水伊布'},
    135: {'fr': 'VOLTALI', 'de': 'BLITZA', 'zh': '雷伊布'},
    136: {'fr': 'PYROLI', 'de': 'FLAMARA', 'zh': '火伊布'},
    137: {'zh': '多边兽'},
    138: {'fr': 'AMONITA', 'de': 'AMONITAS', 'zh': '菊石兽'},
    139: {'fr': 'AMONISTAR', 'de': 'AMOROSO', 'zh': '多刺菊石兽'},
    140: {'zh': '化石盔'},
    141: {'zh': '镰刀盔'},
    142: {'fr': 'PTERA', 'zh': '化石翼龙'},
    143: {'fr': 'RONFLEX', 'de': 'RELAXO', 'zh': '卡比兽'},
    144: {'fr': 'ARTIKODIN', 'de': 'ARKTOS', 'zh': '急冻鸟'},
    145: {'fr': 'ELECTHOR', 'zh': '闪电鸟'},
    146: {'fr': 'SULFURA', 'de': 'LAVADOS', 'zh': '火焰鸟'},
    147: {'fr': 'MINIDRACO', 'zh': '迷你龙'},
    148: {'fr': 'DRACO', 'de': 'DRAGONIR', 'zh': '哈克龙'},
    149: {'fr': 'DRACOLOSSE', 'de': 'DRAGORAN', 'zh': '快龙'},
    150: {'de': 'MEWTU', 'zh': '超梦'},
    151: {'zh': '梦幻'},
}
